/** Legacy GIS bundle snippet: lat/lon + geometry on analysis reports for community panel. */

export default [
  'function pointWgsFrom32643Point(anchor32643) {',
  '  if (!anchor32643 || anchor32643.type !== "point") return null;',
  '  return projection.load().then(function () {',
  '    var pWgs = projection.project(anchor32643, SR4326);',
  '    if (!pWgs || !isValidWgsLatLon(Number(pWgs.y), Number(pWgs.x))) return null;',
  '    return { lat: Number(pWgs.y), lon: Number(pWgs.x) };',
  '  }).catch(function () {',
  '    return null;',
  '  });',
  '}',
  '',
  'function geometryJsonFrom32643(geom32643) {',
  '  if (!geom32643) return null;',
  '  try {',
  '    return geom32643.toJSON ? geom32643.toJSON() : null;',
  '  } catch (e0) {',
  '    return null;',
  '  }',
  '}',
  '',
  'function buildAnalysisPlaceContextExtras(anchor32643, summaryGeom32643, radiusM) {',
  '  var extras = {};',
  '  var rad = Number(radiusM);',
  '  if (isFinite(rad) && rad > 0) extras.radiusM = Math.round(rad);',
  '  var gj = geometryJsonFrom32643(summaryGeom32643);',
  '  if (gj) {',
  '    extras.summaryGeometryJson = gj;',
  '    extras.queryGeometryJson = gj;',
  '  }',
  '  return pointWgsFrom32643Point(anchor32643).then(function (wgs) {',
  '    if (wgs) {',
  '      extras.lat = wgs.lat;',
  '      extras.lon = wgs.lon;',
  '    } else if (summaryGeom32643) {',
  '      return projection.load().then(function () {',
  '        var g326 = toEngineSR(ensureSR32643(summaryGeom32643));',
  '        if (!g326) return extras;',
  '        var ctr = g326.type === "point" ? g326 : getGeometryCentroid(g326);',
  '        if (!ctr || ctr.type !== "point") return extras;',
  '        return pointWgsFrom32643Point(ctr).then(function (wgs2) {',
  '          if (wgs2) {',
  '            extras.lat = wgs2.lat;',
  '            extras.lon = wgs2.lon;',
  '          }',
  '          return extras;',
  '        });',
  '      }).catch(function () {',
  '        return extras;',
  '      });',
  '    }',
  '    return extras;',
  '  });',
  '}',
  '',
  'function withPlaceLookupTimeout(promise, ms) {',
  '  var timeoutMs = isFinite(Number(ms)) && Number(ms) > 0 ? Number(ms) : 8000;',
  '  return Promise.race([',
  '    Promise.resolve(promise).catch(function () { return null; }),',
  '    new Promise(function (resolve) {',
  '      window.setTimeout(function () { resolve(null); }, timeoutMs);',
  '    })',
  '  ]);',
  '}',
  '',
  'function attachPlaceAndAssemblyDetailsToPayload(payload) {',
  '  if (!payload) return Promise.resolve(null);',
  '  var lat = Number(payload.lat);',
  '  var lon = Number(payload.lon);',
  '  if (!isFinite(lat) || !isFinite(lon)) return Promise.resolve(payload);',
  '  var point = { lat: lat, lon: lon };',
  '  var tasks = [];',
  '  if (typeof window !== "undefined" && typeof window.msmeGisQueryPlaceDetailsByPointWgs84 === "function") {',
  '    tasks.push(',
  '      withPlaceLookupTimeout(window.msmeGisQueryPlaceDetailsByPointWgs84(point), 8000).then(function (placeDetails) {',
  '        if (!placeDetails) return;',
  '        payload.placeDetails = placeDetails;',
  '        if (!payload.domContext) payload.domContext = {};',
  '        payload.domContext.placeDetails = placeDetails;',
  '      }).catch(function () {})',
  '    );',
  '  }',
  '  if (typeof window !== "undefined" && typeof window.msmeGisQueryAssemblyDetailsByPointWgs84 === "function") {',
  '    tasks.push(',
  '      withPlaceLookupTimeout(window.msmeGisQueryAssemblyDetailsByPointWgs84(point), 8000).then(function (assemblyDetails) {',
  '        if (!assemblyDetails) return;',
  '        payload.assemblyDetails = assemblyDetails;',
  '        if (!payload.domContext) payload.domContext = {};',
  '        payload.domContext.assemblyDetails = assemblyDetails;',
  '      }).catch(function () {})',
  '    );',
  '  }',
  '  if (!tasks.length) return Promise.resolve(payload);',
  '  return Promise.all(tasks).then(function () {',
  '    return payload;',
  '  });',
  '}',
  '',
  'function publishAnalysisToolResultWithPlaceContext(toolId, summary, extra, anchor32643, summaryGeom32643, radiusM) {',
  '  return buildAnalysisPlaceContextExtras(anchor32643, summaryGeom32643, radiusM).then(function (ctx) {',
  '    var payload = publishAnalysisToolResult(toolId, summary, Object.assign({}, extra || {}, ctx || {}));',
  '    return attachPlaceAndAssemblyDetailsToPayload(payload).then(function (finalPayload) {',
  '      try {',
  '        if (typeof window !== "undefined" && window.dispatchEvent) {',
  '          window.dispatchEvent(new CustomEvent("msme-community-panel-open"));',
  '        }',
  '      } catch (eOpen) {}',
  '      return finalPayload;',
  '    });',
  '  });',
  '}',
  '',
  'function enrichReportSnapshotWithPlaceContext(basePayload, anchor32643, summaryGeom32643) {',
  '  if (!basePayload) return Promise.resolve(null);',
  '  return buildAnalysisPlaceContextExtras(anchor32643, summaryGeom32643, basePayload.radiusM).then(function (ctx) {',
  '    var enriched = {};',
  '    Object.keys(basePayload).forEach(function (k) {',
  '      enriched[k] = basePayload[k];',
  '    });',
  '    Object.keys(ctx || {}).forEach(function (k2) {',
  '      if (enriched[k2] == null || enriched[k2] === "") enriched[k2] = ctx[k2];',
  '    });',
  '    return attachPlaceAndAssemblyDetailsToPayload(enriched);',
  '  });',
  '}',
  '',
].join('\n')
